name: Test

on:
  push:
    branches: [dev, main, uat]

jobs:
  test:
    name: Test
    runs-on: [self-hosted, linux, docker]
    steps:
      - name: Checkout
        run: |
          rm -rf /repo /git-repo 2>/dev/null || true
          git clone --depth=1 --branch=${{ github.ref_name }} https://github.com/${{ github.repository }}.git /repo
          cd /repo
          git fetch origin ${{ github.ref_name }}
          git checkout ${{ github.sha }}

      - name: Run tests
        run: |
          echo "Running tests..."
          whoami && pwd && ls /repo
          echo "Tests passed!"
