services:
  act-runner:
    image: gitea/act_runner:latest
    container_name: act-runner
    restart: unless-stopped
    environment:
      - GITEA_INSTANCE_URL=http://10.8.0.10:3000
      - GITEA_RUNNER_CAPACITY=2
      - GITEA_RUNNER_NAME=nas-act-runner
      - GITEA_RUNNER_LABELS=self-hosted,linux,docker
      - GITEA_RUNNER_TOKEN=IoDdKg2Xlid8eBsScH7LwTAQwqZJ1oh7YbJZ5EkJ
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /volume1/Docker/act-runner/runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3030:3030"
